### ISSUE TITLE
Setting maven property "buildtime.output.log" does not output report

### ISSUE THREAD

**Issue by aramesh117** [timgifford/maven-buildtime-extension#33]
Only the commandline argument "-Dbuildtime.output.log" activates the report during normal runs.

The maven property <buildtime.output.log>true</buildtime.output.log> does not do anything. Is this intended?

**Comment by aramesh117** [comment]
After some investigation, it appears that maven properties aren't exposed in the MavenSession's userProperties or systemProperties list. It's exposed only using the project. Checking whether the property exists `mavenSession.getCurrentProject().getProperties()` works. I can send a patch. Can @timgifford comment on whether this makes sense?

**Comment by aramesh117** [comment]
Unfortunately, I'm not able to dedicate more time to this, but the primary patch is:
```
diff --git a/src/main/java/co/leantechniques/maven/buildtime/MavenHelper.java b/src/main/java/co/leantechniques/maven/buildtime/MavenHelper.java
index 2f7888b..dec96f4 100644
--- a/src/main/java/co/leantechniques/maven/buildtime/MavenHelper.java
+++ b/src/main/java/co/leantechniques/maven/buildtime/MavenHelper.java
@@ -10,10 +10,12 @@ public class MavenHelper {
 
     public static String getExecutionProperty(final ExecutionEvent event, final String property, final String def) {
         MavenSession mavenSession = event.getSession();
+        Properties projectProperties = mavenSession.getCurrentProject().getProperties();
         Properties systemProperties = mavenSession.getSystemProperties();
         Properties userProperties = mavenSession.getUserProperties();
         String output = userProperties.getProperty(property);
         output = output == null ? systemProperties.getProperty(property) : output;
+        output = output == null ? projectProperties.getProperty(property) : output;
         return output == null ? def : output;
     }
 }
```

in addition to fixing the tests to mock session to return a project and fixing the it-tests.

**Comment by jfcroteau** [comment]
I tried your patch, but my mavenSession.getCurrentProject() == null. I have the property in the 
mavenSession.getTopLevelProject().getProperties().

If I can have access, I could push my branch and create a pull request for the patch.

**Comment by jfcroteau** [comment]
See https://github.com/timgifford/maven-buildtime-extension/pull/39

**Comment by mithuns** [comment]
Even passing `-Dbuildtime.output.log=true` while doing `mvn clean install` from command prompt does not produce run-time analysis for me. So, I hope this fixes that.

**Comment by jfcroteau** [comment]
I have fixed the indentation. You can now check the pull request https://github.com/timgifford/maven-buildtime-extension/pull/39.

Sorry for the delay.

**Comment by maassql** [comment]
Wanted to contribute this.  Wrote it before I looked here.  :(

```
# -------------------------------------------------------------------------
# -------- REPRODUCTION SCRIPT --------------------------------------------
VERSION=3.0.3
logfile='maven-buildtime-extension.log'
mvn --quiet dependency:get -Dartifact="co.leantechniques:maven-buildtime-extension:$VERSION" --log-file="${logfile}"
mvn clean --log-file="${logfile}"
build_time_path="$HOME/.m2/repository/co/leantechniques/maven-buildtime-extension/$VERSION/maven-buildtime-extension-$VERSION.jar"
write_results_to_csv='-Dbuildtime.output.log=true -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv'
use_build_time_extension=-Dmaven.ext.class.path="${build_time_path} ${write_results_to_csv}"
mvn --debug --show-version compile "${use_build_time_extension}" --log-file="${logfile}"
head -n 6 "${logfile}"
find . -name 'maven*'
grep 'BuildTimeEventSpy' "${logfile}"
grep 'maven-buildtime-extension' "${logfile}"
# -------- REPRODUCTION SCRIPT --------------------------------------------
# -------------------------------------------------------------------------
```




```
# -------------------------------------------------------------------------
# ------- OUTPUT ----------------------------------------------------------
$ --->head -n 6 "${logfile}"
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
Maven home: /usr/local/maven/apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"






$ --->find . -name 'maven*'
./maven-buildtime-extension.log
./project_configuration_recorder/maven-pmd-plugin-default.xml
./target/maven-status
./target/maven-status/maven-compiler-plugin



$ --->grep 'BuildTimeEventSpy' "${logfile}"



$ --->grep 'maven-buildtime-extension' "${logfile}"
[DEBUG]   Included /Users/{bleached}/.m2/repository/co/leantechniques/maven-buildtime-extension/3.0.3/maven-buildtime-extension-3.0.3.jar -Dbuildtime.output.log=true -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv
[DEBUG]   Included /Users/{bleached}/.m2/repository/co/leantechniques/maven-buildtime-extension/3.0.3/maven-buildtime-extension-3.0.3.jar -Dbuildtime.output.log=true -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv
[DEBUG] properties used {java.vendor=Oracle Corporation
 , awt.toolkit=sun.lwawt.macosx.LWCToolkit
 , buildNumber=2018-08-31T20:05:21.310+0000
 , classworlds.conf=/usr/local/maven/apache-maven-3.5.0/bin/m2.conf
 , dataloader.shared-version=1.0.5
 , env.Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.aWstRWuO6d/Render
 , env.CLICOLOR=1
 , env.COLORFGBG=7;0
 , env.COMMAND_MODE=unix2003
 , env.GROOVY_HOME=/Users/{bleached}/.sdkman/candidates/groovy/current
 , env.HISTTIMEFORMAT=%d/%m/%y %T 
 , env.HOME=/Users/{bleached}
 , env.ITERM_SESSION_ID=w1t2p0:E2022EAE-DD12-4223-8A0D-2E3E50EA0075
 , env.JAVA_ARCH=x86_64
 , env.JAVA_MAIN_CLASS_30361=org.codehaus.plexus.classworlds.launcher.Launcher
 , env.LANG=en_US.UTF-8
 , env.LOGNAME={bleached}
 , env.LSCOLORS=GxFxCxDxBxegedabagaced
 , env.MAVEN_CMD_LINE_ARGS= --debug --show-version compile -Dmaven.ext.class.path=/Users/{bleached}/.m2/repository/co/leantechniques/maven-buildtime-extension/3.0.3/maven-buildtime-extension-3.0.3.jar -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv --log-file=maven-buildtime-extension.log
 , env.OLDPWD={bleached}
 , env.PATH=/Users/{bleached}/.sdkman/candidates/groovy/current/bin:/usr/local/maven/apache-maven-3.5.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
 , env.PWD={bleached}
 , env.SDKMAN_CANDIDATES_DIR=/Users/{bleached}/.sdkman/candidates
 , env.SDKMAN_CURRENT_API=https://api.sdkman.io/2
 , env.SDKMAN_DIR=/Users/{bleached}/.sdkman
 , env.SDKMAN_LEGACY_API=https://api.sdkman.io/1
 , env.SDKMAN_PLATFORM=Darwin
 , env.SDKMAN_VERSION=5.6.5+313
 , env.SECURITYSESSIONID=186a6
 , env.SHELL=/bin/bash
 , env.SHLVL=1
 , env.SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ieNT168571/Listeners
 , env.TERM=xterm-256color
 , env.TERM_PROGRAM=iTerm.app
 , env.TERM_PROGRAM_VERSION=3.1.7
 , env.TERM_SESSION_ID=w1t2p0:E2022EAE-DD12-4223-8A0D-2E3E50EA0075
 , env.TMPDIR=/var/folders/ql/jg944vg93g18j8ckw3rr0qz00000gn/T/
 , env.USER={bleached}
 , env.XPC_FLAGS=0x0
 , env.XPC_SERVICE_NAME=0
 , env.__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
 , env.com.apple.java.jvmTask=CommandLine
 , file.encoding.pkg=sun.io
 , file.separator=/
 , ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
 , gopherProxySet=false
 , hsp-dlp-version=1.0.14
 , http.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
 , java-version=1.8
 , java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
 , java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
 , java.class.path=/usr/local/maven/apache-maven-3.5.0/boot/plexus-classworlds-2.5.2.jar
 , java.class.version=52.0
 , java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/endorsed
 , java.ext.dirs=/Users/{bleached}/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
 , java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
 , java.io.tmpdir=/var/folders/ql/jg944vg93g18j8ckw3rr0qz00000gn/T/
 , java.library.path=/Users/{bleached}/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
 , java.runtime.name=Java(TM) SE Runtime Environment
 , java.runtime.version=1.8.0_144-b01
 , java.specification.name=Java Platform API Specification
 , java.specification.vendor=Oracle Corporation
 , java.vendor.url.bug=http://bugreport.sun.com/bugreport/
 , java.vendor.url=http://java.oracle.com/
 , java.version=1.8.0_144
 , java.vm.info=mixed mode
 , java.vm.specification.name=Java Virtual Machine Specification
 , java.vm.specification.vendor=Oracle Corporation
 , java.vm.specification.version=1.8
 , java.vm.vendor=Oracle Corporation
 , java.vm.version=25.144-b01
 , library.jansi.path=/usr/local/maven/apache-maven-3.5.0/lib/jansi-native/osx64
 , line.separator=
 , maven.build.timestamp.format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
 , maven.build.version=Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
 , maven.compile.source=1.8
 , maven.compile.target=1.8
 , maven.conf=/usr/local/maven/apache-maven-3.5.0/conf
 , maven.ext.class.path=/Users/{bleached}/.m2/repository/co/leantechniques/maven-buildtime-extension/3.0.3/maven-buildtime-extension-3.0.3.jar -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv
 , maven.home=/usr/local/maven/apache-maven-3.5.0
 , maven.multiModuleProjectDirectory=/Users/{bleached}/Documents/repos/{bleached}
 , maven.version=3.5.0
 , org.slf4j.simpleLogger.defaultLogLevel=debug
 , os.arch=x86_64
 , os.name=Mac OS X
 , os.version=10.12.6
 , path.separator=:
 , project.build.sourceEncoding=UTF-8
 , project.reporting.outputEncoding=UTF-8
 , socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16
 , sun.arch.data.model=64
 , sun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/classes
 , sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib
 , sun.cpu.endian=little
 , sun.cpu.isalist=
 , sun.io.unicode.encoding=UnicodeBig
 , sun.java.command=org.codehaus.plexus.classworlds.launcher.Launcher --debug --show-version compile -Dmaven.ext.class.path=/Users/{bleached}/.m2/repository/co/leantechniques/maven-buildtime-extension/3.0.3/maven-buildtime-extension-3.0.3.jar -Dbuildtime.output.csv=true -Dbuildtime.output.csv.file=maven-buildtime-extension.csv --log-file=maven-buildtime-extension.log
 , sun.java.launcher=SUN_STANDARD
 , sun.jnu.encoding=UTF-8
 , sun.management.compiler=HotSpot 64-Bit Tiered Compilers
 , sun.os.patch.level=unknown
 , user.country=US
 , user.dir=/Users/{bleached}/Documents/repos/{bleached}
 , user.home=/Users/{bleached}
 , user.language=en
 , user.name={bleached}
 , user.timezone=America/Chicago

# ------- OUTPUT ----------------------------------------------------------
# -------------------------------------------------------------------------
```

**Comment by Jan-Thes** [comment]
Hello,

i am using the latest 3.0.3 release version and i still have the same issue:

The following pom.xml content does nothing (i only get `[INFO] BuildTimeEventSpy is registered.`) when running `mvn package`.
```
<properties>
                <!-- Always enable Maven Buildtime Extension from .mvn folder -->
		<buildtime.output.log>true</buildtime.output.log>
</properties>
```

Only when i run `mvn "-Dbuildtime.output.log=true" package` do i get the output of the plugin (`[INFO] Build Time Summary: ...`) in the command line.

I use default logging/output settings, running in Powershell on Windows 11 on OpenJDK 11.

**Comment by timgifford** [comment]
@Jan-Thes which version of Maven are you using? It’s been many years since I worked in this, but have a vague memory of it not working in the latest version of mvn.

**Comment by nedy13** [comment]
Same issue here:

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Java version: 11.0.16.1, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by laymain** [comment]
The latest commit that fixes this issue has never been released, that's why it is not working.

@timgifford @jfcroteau Could you please release a 3.0.4 version?

**Comment by timgifford** [comment]
@laymain  @mithuns I've released 3.0.5.
